### ISSUE TITLE
run GC before logging mem stats

### ISSUE THREAD

**Issue by JensEggers** [happner/benchmarket#2]
benchmarket to throw error if GC not enabled

**Comment by nomilous** [comment]
setting called `requireGC`, will NOT post data unless --expose-gc was passed

**Comment by nomilous** [comment]
- does GC immediately before and after every test (it)
- test reported duration not affected by GC time
- config.requireGC can be set to false to disable
- if --expose-gc was passed then no heapDelta metric is submitted, duration metric is still submitted
